### ISSUE TITLE
SyntaxError: The requested module 'node:module' does not provide an export named 'findPackageJSON'

### ISSUE THREAD

**Issue by sibelius** [nodejs-loaders/nodejs-loaders#64]
I'm getting this error

```
node --experimental-strip-types --loader=@nodejs-loaders/tsx "index.ts"


node:internal/modules/run_main:122
    triggerUncaughtException(
    ^
file:///root/app/node_modules/@nodejs-loaders/tsx/find-esbuild-config.mjs:1
import { createRequire, findPackageJSON } from 'node:module';
                        ^^^^^^^^^^^^^^^
SyntaxError: The requested module 'node:module' does not provide an export named 'findPackageJSON'
```

**Comment by AugustinMauroy** [comment]
Hey ! Happy to see that our loaders is used.

First, if you have this error it's mean you need to use a newest version of node.js. 
Second don't enable types stripping with tsx loader. Because of the ["chaining"](https://nodejs.org/docs/latest/api/module.html#chaining), `tsx` loader will transform typescript then node.js will try to strip types so more things todo mean impact on pref.
Third, I'm sorry but actual version of `tsx` loader is broken 😭 (REF: #53). But if you really needed we can found quick patch for you 😁

**Comment by JakobJingleheimer** [comment]
Yes, your current error is from using an outdated version of node.

The current version of nodejs-loaders/tsx is broken by a bug in node. A fix for that node bug is currently in progress.

There is an older version of nodejs-loaders that is not broken by the node bug: https://www.npmjs.com/package/nodejs-loaders. There is no migration effort for switching between the 2 versions (aside from changing the dependency); the newer version is just smaller and more efficient.

**Comment by sibelius** [comment]
I'm using latest node version LTS, node 22

**Comment by AugustinMauroy** [comment]
for now it's only 23.

**Comment by JakobJingleheimer** [comment]
> I'm using latest node version LTS, node 22

`findPackageJSON` will be in node 22.13 (see tsx/package.json), which will be released soon. `findPackageJSON` a backport to 20.x has been requested, but there is no ETA for that.

**Comment by JakobJingleheimer** [comment]
@sibelius heads up: the fix to `@nodejs-loader/tsx` (https://github.com/nodejs-loaders/nodejs-loaders/pull/70) is just waiting on the next node release, which is currently planned for 07 January.
